### ISSUE TITLE
Skypack complaining

### ISSUE THREAD

**Issue by AZMCode** [DevSnowflake/youtube-sr#10]
Hello! I´m a new user to this library (Which looks amazing btw), and have been trying it on Deno, however it seems when i call the `search` static method, skypack complains like so:

```
error: Uncaught (in promise) TypeError: node_fetch_1.default is not a function
        node_fetch_1.default(url, prop).then((res) => res.text()).then((html) => resolve(html)).catch((e) => reject(e));
                            ^
    at https://cdn.skypack.dev/-/youtube-sr@v3.0.0-9EZGCmCqXXj9Rp9BSVMd/dist=es2020/youtube-sr.js:269:29
    at new Promise (<anonymous>)
    at Function.getHTML (https://cdn.skypack.dev/-/youtube-sr@v3.0.0-9EZGCmCqXXj9Rp9BSVMd/dist=es2020/youtube-sr.js:267:14)
    at Function.search (https://cdn.skypack.dev/-/youtube-sr@v3.0.0-9EZGCmCqXXj9Rp9BSVMd/dist=es2020/youtube-sr.js:527:43)
    at getYoutubeVideo (mod.ts:26:35)
    at resolve (mod.ts:21:31)
    at async test.ts:7:9
```
The last three lines of the stack are mine, but I believe the rest might need some tweaking. I'll provide feedback on the bug as soon as requested. If any help finding this bug is needed, I'll drop in to the source code to help squash this. Cheerio!

**Comment by Snowflake107** [comment]
🤔can you send your code here?

**Comment by AZMCode** [comment]
In a moment

**Comment by AZMCode** [comment]
```
import { YouTube } from "https://deno.land/x/youtube_sr/mod.ts";

await YouTube.search("Diddly Daddily");
```

**Comment by Snowflake107** [comment]
@AZMCode hmm weird, tested  your code just now and it works fine 🙄

**Comment by AZMCode** [comment]
![Image.png](https://user-images.githubusercontent.com/15837568/106279761-4ff09680-6213-11eb-9579-09a46c4ba323.png)

**Comment by AZMCode** [comment]
Any troubleshooting I can do to pin this down? Already tried reloading demo cache but no result yet.

**Comment by Snowflake107** [comment]
@AZMCode hm let me see again, maybe I was running cached version

**Comment by AZMCode** [comment]
Just updated deno to check it wasn't a Deno bug.

**Comment by Snowflake107** [comment]
Thanks, I was running cached version, I will try to fix this asap 😊

**Comment by AZMCode** [comment]
Thanks mate

**Comment by AZMCode** [comment]
Went through the code a bit, it seems the error is being emitted from line 48 of Utils.ts

**Comment by AZMCode** [comment]
It's as if fetch wasn't a function, which is wild.

**Comment by AZMCode** [comment]
I sure hope this isn't a skypack bug.

**Comment by Snowflake107** [comment]
🤔It should work now. (v3.0.3)

**Comment by AZMCode** [comment]
It indeed does. Thank you!

**Comment by Snowflake107** [comment]
👍
