### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by mpirescarvalho** [DevSnowflake/youtube-sr#16]
Cannot build after upgrading to **4.0.3**

![image](https://user-images.githubusercontent.com/20830847/113949611-0e1d3700-97e6-11eb-8be9-4e4c5446f77c.png)
Seems like it's point to the `optional chaining operator (?)` ?

I'm already using node 14.x
![image](https://user-images.githubusercontent.com/20830847/113949670-2e4cf600-97e6-11eb-9b45-c186dfffd387.png)

Here's my webpack rule for js files:
![image](https://user-images.githubusercontent.com/20830847/113949902-71a76480-97e6-11eb-8830-e96f8c678ee5.png)

And here's my babel config:
![image](https://user-images.githubusercontent.com/20830847/113949956-8f74c980-97e6-11eb-9108-ca7df2192888.png)

I tried adding `@babel/plugin-proposal-optional-chaining` but it didn't work

Any insights?

**Comment by Snowflake107** [comment]
@mpirescarvalho try using `v4.0.4`

**Comment by mpirescarvalho** [comment]
It worked, thanks!
