### ISSUE TITLE
Playlist videos

### ISSUE THREAD

**Issue by mpirescarvalho** [DevSnowflake/youtube-sr#20]
It's possible to fetch more than 100 videos in a playlist?

This is the code I'm using:
![image](https://user-images.githubusercontent.com/20830847/116488356-91bbc800-a868-11eb-9001-96f90f211c09.png)
Result:
`{ videoCount: 551, actualVideos: 100 }`

I saw that the `limit` defaults to 100, but I couldn't get more than that. I also tried with others limits values such as:
`.getPlaylist(playlistUrl, { limit: 0 })`
`.getPlaylist(playlistUrl, { limit: undefined })`
`.getPlaylist(playlistUrl)`

**Comment by Snowflake107** [comment]
with this package, I don't think it is possible to get more than 100 items :thinking:

however, you can use **[ytpl](https://npmjs.com/package/ytpl)** which is focused on youtube playlists parsing

**Comment by Snowflake107** [comment]
I have added `Playlist.next()` and `Playlist.fetch()` methods to solve this in `v4.0.10`. The `next` method returns next 100 items whereas `fetch` fetches every possible items (slow).

**Comment by Snowflake107** [comment]
@mpirescarvalho is lazy loading playlist with `Playlist.next()` okay for you?

**Comment by mpirescarvalho** [comment]
I haven't tested it yet, but I'll do it by tomorrow
