### ISSUE TITLE
Related videos

### ISSUE THREAD

**Issue by mpirescarvalho** [DevSnowflake/youtube-sr#22]
Is there a way to get related/suggested videos of a video?

![image](https://user-images.githubusercontent.com/20830847/119509213-d2631000-bd46-11eb-8392-a371aebc44a2.png)

**Comment by Snowflake107** [comment]
Yes, would need to modify `YouTube.getVideo`

**Comment by mpirescarvalho** [comment]
Do you have plans to implement it?

**Comment by Snowflake107** [comment]
Yes I will do it today

**Comment by Snowflake107** [comment]
done in https://github.com/DevSnowflake/youtube-sr/releases/tag/v4.0.9
