### ISSUE TITLE
TypeError, undefined is not iterable

### ISSUE THREAD

**Issue by TehRamsus** [DevSnowflake/youtube-sr#23]
Hey
For some reason this code went wrong:     

```js
 const searchres = await YouTube.getVideo(args[0]);
            const Title = searchres.title;
            console.log(Title)
```

And I got this error: 
![image](https://user-images.githubusercontent.com/50022415/120893268-12fe3b80-c61b-11eb-82e9-48e3c553ea25.png)

So what is the problem? :D

**Comment by Snowflake107** [comment]
odd, may I see your `args[0]`?

**Comment by TehRamsus** [comment]
Yeah, it's something like this: 
`js const args = message.content.slice(Config.prefix.length).trim().split(/ +/);`

**Comment by Snowflake107** [comment]
I mean, what was your `args[0]`? is it a valid youtube video link?

**Comment by TehRamsus** [comment]
aah, yeah it's youtube link.

**Comment by sujalgoel** [comment]
can you please share that link.

**Comment by TehRamsus** [comment]
aah damn, it was age restricted video :D I didn't noticed that, because with search function it works :D

**Comment by sujalgoel** [comment]
ok

**Comment by Snowflake107** [comment]
I've fixed this error on the latest version
