### ISSUE TITLE
Limite

### ISSUE THREAD

**Issue by GIOVANNI-75** [DevSnowflake/youtube-sr#4]
hello, how can we do to increase the response limit over of 20? (in search the limit of my results is 18 items max)

**Comment by Snowflake107** [comment]
try something like this `youtube.search("query", { limit: 100 })`

**Comment by GIOVANNI-75** [comment]
I already try to change the limit options, it returns to me every time a limit of 18 items

**Comment by Snowflake107** [comment]
@GIOVANNI-75 looks like YouTube returns total 24 results and filtering them by video dropped down to 18 :/

I will see if I can increase the limit 👍

**Comment by GIOVANNI-75** [comment]
Merci beaucoup 👍
