### ISSUE TITLE
Playlist Regex: support more URLs

### ISSUE THREAD

**Issue by Androz2091** [DevSnowflake/youtube-sr#5]
It would be nice if the playlist regex could accept these types of links:
- `https://www.youtube.com/playlist?list=PLfdVffIikakx-BD5BlCvEHVRlZKKCbqXg` (it already works)
- `https://www.youtube.com/watch?list=PLfdVffIikakx-BD5BlCvEHVRlZKKCbqXg`
- `https://www.youtube.com/watch?v=astISOttCQ0&list=PLfdVffIikakx-BD5BlCvEHVRlZKKCbqXg`

**Comment by Snowflake107** [comment]
So, `https://www.youtube.com/watch?list=PLfdVffIikakx-BD5BlCvEHVRlZKKCbqXg` and `https://www.youtube.com/watch?v=astISOttCQ0&list=PLfdVffIikakx-BD5BlCvEHVRlZKKCbqXg` should return `https://www.youtube.com/playlist?list=PLfdVffIikakx-BD5BlCvEHVRlZKKCbqXg` as final url

**Comment by Snowflake107** [comment]
Should work on v2.0.2 **[480064fd94](https://github.com/DevSnowflake/youtube-sr/commit/480064fd942ca2a080bc618e59b349f07796fc0a)**
