### ISSUE TITLE
max result limit to 20 videos

### ISSUE THREAD

**Issue by xOldeVx** [DevSnowflake/youtube-sr#6]
First of all, very nice work.
I need to get more than 20 results, the youtube-sr return max of 20 videos.
1. there is an option to get more than 20 videos in one call?
2. there is an option to get more another 20 videos?

**Comment by Snowflake107** [comment]
I don't think so because there's total 20-22 videos available inside raw json on youtube page :(

You can try using **[ytsr](https://npmjs.com/package/ytsr)** because it scrapes data from the page instead of `script` tag

**Comment by xOldeVx** [comment]
ohh.. it's a big drawback, only 20-22 results is not really useful.
i think if you support the features i noted above, it's can make this library a big success
