### ISSUE TITLE
getPlaylist is not a function

### ISSUE THREAD

**Issue by BlazeDexX** [DevSnowflake/youtube-sr#9]
I am using the latest version but i got error getPlaylist is not a function
const ytsr = require('youtube-sr');
ytsr.getPlaylist('https://www.youtube.com/playlist?list=PL1qh5tjST4TgIn4evBqGs9hR8D0JD5rlI');
![image](https://user-images.githubusercontent.com/67855694/104805744-e29d3880-5804-11eb-9c80-e36d8e8e7f8b.png)

**Comment by Snowflake107** [comment]
@BlazeDexX try using `ytsr.default.getPlaylist()`

**Comment by BlazeDexX** [comment]
> @BlazeDexX try using `ytsr.default.getPlaylist()`

ahh it's work.
